version: 0.2
 
phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 562773714884.dkr.ecr.ap-south-1.amazonaws.com
      - echo "Running Django tests"
      - python manage.py test
 
  build:
    commands:
      - echo "Building the Docker image for backend"
      - docker build -t expensify-backend .
      - docker tag expensify-backend:latest 562773714884.dkr.ecr.ap-south-1.amazonaws.com/expensify-backend:latest
      - echo "Pushing the Docker image to ECR"
      - docker push 562773714884.dkr.ecr.ap-south-1.amazonaws.com/expensify-backend:latest
 
artifacts:
  files:
    - "**/*"