# Generated by Django 5.1 on 2024-09-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_budget_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
