# Generated by Django 5.1 on 2024-09-10 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_budget_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('february', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('march', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('april', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('may', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('june', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('july', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('august', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('september', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('october', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('november', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('december', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_monthly', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
