# Generated by Django 5.1 on 2024-09-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_budgetmonthly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='budgetmonthly',
            name='april',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='budgetmonthly',
            name='august',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='budgetmonthly',
            name='december',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='budgetmonthly',
            name='february',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='budgetmonthly',
            name='january',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='budgetmonthly',
            name='july',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='budgetmonthly',
            name='june',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='budgetmonthly',
            name='march',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='budgetmonthly',
            name='may',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='budgetmonthly',
            name='november',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='budgetmonthly',
            name='october',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='budgetmonthly',
            name='september',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='budgetmonthly',
            name='total_amount',
            field=models.IntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.IntegerField(max_length=10),
        ),
    ]
