# Generated by Django 5.1 on 2024-09-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_budget_amount_alter_budgetmonthly_april_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('member', 'Member')], default='user', max_length=10),
        ),
    ]
